spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: cars-service
              uri: http://cars-service:8080
              predicates:
                - Path=/api/cars/**
            - id: owners-service
              uri: http://owners-service:8080
              predicates:
                - Path=/api/owners/**
            - id: agents-service
              uri: http://agents-service:8080
              predicates:
                - Path=/api/agents/**
            - id: registration-service
              uri: http://registration-service:8080
              predicates:
                - Path=/api/registrations/**

server:
  port: 8080